import Head from "next/head";
import Content1 from "../components/front-page/Content1";
import Content2 from "../components/front-page/Content2";
// import Hero from "../components/Hero";
import Hero1 from "../components/hero/Hero1";
import ServiceArea from "../components/ServiceArea";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dogbiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero1 />
      <Content1 />
      <Content2 />
      {/* <ServiceArea /> */}
    </>
  );
}
